namespace OmlTerminal.Core.CliGuide;

public static partial class CliGuideData
{
    private static CliCommand C(string cmd, string desc, CliMode mode, string cat, string syntax = "", string ex = "")
        => new(cmd, desc, mode, cat, syntax, ex);

    private static CliVendor CiscoIos() => new("cisco-ios", "Cisco IOS / IOS-XE", "Router#",
    [
        // Show / verify
        C("show running-config", "Display the active running configuration in memory.", CliMode.Privileged, "Show & verify", "show running-config [interface <if>| | section <text>]", "show running-config | section bgp"),
        C("show startup-config", "Display the saved configuration loaded at boot.", CliMode.Privileged, "Show & verify"),
        C("show ip interface brief", "One-line status and IP of every interface.", CliMode.Exec, "Show & verify", "show ip interface brief", "show ip interface brief | include up"),
        C("show interfaces status", "Switchport link, VLAN, duplex and speed table.", CliMode.Exec, "Show & verify"),
        C("show interfaces <if>", "Detailed counters, errors and state for one interface.", CliMode.Exec, "Show & verify", "show interfaces GigabitEthernet0/1", "show interfaces Gi0/1 | include error"),
        C("show version", "IOS version, uptime, model, serial and config register.", CliMode.Exec, "Show & verify"),
        C("show inventory", "Hardware modules with serial and product IDs.", CliMode.Exec, "Show & verify"),
        C("show ip route", "The IPv4 routing table.", CliMode.Exec, "Routing", "show ip route [<prefix> | ospf | bgp | static]", "show ip route 10.0.0.0"),
        C("show ip protocols", "Running routing protocols and their parameters.", CliMode.Exec, "Routing"),
        C("show cdp neighbors", "Directly connected Cisco devices (add 'detail' for IPs).", CliMode.Exec, "Discovery", "show cdp neighbors [detail]"),
        C("show lldp neighbors", "Directly connected LLDP devices of any vendor.", CliMode.Exec, "Discovery", "show lldp neighbors [detail]"),
        C("show vlan brief", "VLANs and their assigned access ports.", CliMode.Exec, "Switching"),
        C("show mac address-table", "Learned MAC addresses per port and VLAN.", CliMode.Exec, "Switching", "show mac address-table [address <mac> | vlan <id>]"),
        C("show spanning-tree", "STP roles, states and root bridge per VLAN.", CliMode.Exec, "Switching", "show spanning-tree [vlan <id> | summary]"),
        C("show etherchannel summary", "Port-channel members and bundle status.", CliMode.Exec, "Switching"),
        C("show ip ospf neighbor", "OSPF adjacencies and their states.", CliMode.Exec, "Routing"),
        C("show ip bgp summary", "BGP neighbors, state and prefix counts.", CliMode.Exec, "Routing"),
        C("show logging", "The device log buffer.", CliMode.Exec, "Show & verify", "show logging [ | include <text>]"),
        C("show processes cpu", "CPU utilisation, optionally sorted by process.", CliMode.Exec, "Show & verify", "show processes cpu [sorted | history]"),
        // Config basics
        C("configure terminal", "Enter global configuration mode.", CliMode.Privileged, "Config basics", "configure terminal"),
        C("hostname <name>", "Set the device name (and CLI prompt).", CliMode.Config, "Config basics", "hostname CORE-SW1"),
        C("interface <if>", "Enter interface configuration mode.", CliMode.Config, "Interfaces", "interface GigabitEthernet0/1", "interface range Gi0/1 - 24"),
        C("ip address <ip> <mask>", "Assign an IPv4 address to the interface.", CliMode.ConfigInterface, "Interfaces", "ip address 10.0.0.1 255.255.255.0", "ip address dhcp"),
        C("no shutdown", "Enable (bring up) the interface.", CliMode.ConfigInterface, "Interfaces"),
        C("shutdown", "Administratively disable the interface.", CliMode.ConfigInterface, "Interfaces"),
        C("description <text>", "Add a label to the interface.", CliMode.ConfigInterface, "Interfaces", "description Uplink to core"),
        C("switchport mode access", "Make the port an access (single-VLAN) port.", CliMode.ConfigInterface, "Switching"),
        C("switchport access vlan <id>", "Assign the access port to a VLAN.", CliMode.ConfigInterface, "Switching", "switchport access vlan 20"),
        C("switchport mode trunk", "Make the port a trunk (802.1Q tagged) port.", CliMode.ConfigInterface, "Switching"),
        C("switchport trunk allowed vlan <list>", "Restrict which VLANs a trunk carries.", CliMode.ConfigInterface, "Switching", "switchport trunk allowed vlan 10,20,30"),
        C("vlan <id>", "Create a VLAN and enter VLAN config.", CliMode.Config, "Switching", "vlan 20", "vlan 20\n name USERS"),
        C("ip route <net> <mask> <next-hop>", "Add a static route.", CliMode.Config, "Routing", "ip route 0.0.0.0 0.0.0.0 10.0.0.254"),
        C("router ospf <id>", "Enter OSPF process configuration.", CliMode.Config, "Routing", "router ospf 1", "router ospf 1\n network 10.0.0.0 0.0.0.255 area 0"),
        C("router bgp <as>", "Enter BGP configuration.", CliMode.Config, "Routing", "router bgp 65001"),
        C("write memory", "Save the running config to startup (copy run start).", CliMode.Privileged, "Save & manage", "write memory", "copy running-config startup-config"),
        C("copy running-config <dest>", "Copy the config to TFTP/FTP/flash.", CliMode.Privileged, "Save & manage", "copy running-config tftp:", "copy run tftp://10.0.0.9/core.cfg"),
        C("reload", "Reboot the device (prompts to save).", CliMode.Privileged, "Save & manage", "reload [in <mins> | at <hh:mm>]"),
        C("terminal length 0", "Disable output paging for the session.", CliMode.Exec, "Save & manage"),
        // Troubleshoot
        C("ping <host>", "ICMP reachability test.", CliMode.Exec, "Troubleshoot", "ping 8.8.8.8 [repeat <n> | size <bytes> | source <if>]"),
        C("traceroute <host>", "Trace the L3 path to a host.", CliMode.Exec, "Troubleshoot", "traceroute 8.8.8.8"),
        C("debug <feature>", "Enable real-time debugging (use with care).", CliMode.Privileged, "Troubleshoot", "debug ip ospf adj", "undebug all"),
        C("show tech-support", "Bundle of show output for TAC cases.", CliMode.Privileged, "Troubleshoot"),
    ]);

    private static CliVendor CiscoNxos() => new("cisco-nxos", "Cisco NX-OS", "switch#",
    [
        C("show running-config", "Display the running configuration.", CliMode.Privileged, "Show & verify", "show running-config [<feature>]", "show running-config interface"),
        C("show interface brief", "One-line status of every interface.", CliMode.Exec, "Show & verify"),
        C("show interface status", "Switchport link/VLAN/speed table.", CliMode.Exec, "Show & verify"),
        C("show version", "NX-OS version, uptime and hardware.", CliMode.Exec, "Show & verify"),
        C("show vlan brief", "VLANs and assigned ports.", CliMode.Exec, "Switching"),
        C("show ip route", "IPv4 routing table (in a VRF).", CliMode.Exec, "Routing", "show ip route [vrf <name>]"),
        C("show cdp neighbors", "Connected Cisco devices.", CliMode.Exec, "Discovery", "show cdp neighbors [detail]"),
        C("show vpc", "vPC domain, peer-link and consistency status.", CliMode.Exec, "Switching"),
        C("show port-channel summary", "Port-channel members and status.", CliMode.Exec, "Switching"),
        C("show feature", "Which NX-OS features are enabled.", CliMode.Exec, "Show & verify"),
        C("feature <name>", "Enable a feature (interface-vlan, bgp, lacp, vpc...).", CliMode.Config, "Config basics", "feature interface-vlan", "feature bgp"),
        C("configure terminal", "Enter global configuration mode.", CliMode.Privileged, "Config basics"),
        C("interface <if>", "Enter interface config.", CliMode.Config, "Interfaces", "interface Ethernet1/1"),
        C("ip address <ip>/<prefix>", "Assign an IP (NX-OS uses prefix length).", CliMode.ConfigInterface, "Interfaces", "ip address 10.0.0.1/24"),
        C("no shutdown", "Enable the interface.", CliMode.ConfigInterface, "Interfaces"),
        C("switchport access vlan <id>", "Assign an access VLAN.", CliMode.ConfigInterface, "Switching", "switchport access vlan 20"),
        C("vlan <id>", "Create a VLAN.", CliMode.Config, "Switching", "vlan 20"),
        C("router bgp <as>", "Enter BGP config.", CliMode.Config, "Routing", "router bgp 65001"),
        C("copy running-config startup-config", "Save the configuration.", CliMode.Privileged, "Save & manage", "copy running-config startup-config", "copy run start"),
        C("ping <host>", "ICMP reachability test.", CliMode.Exec, "Troubleshoot", "ping 8.8.8.8 vrf management"),
        C("show logging last <n>", "Show the last N log lines.", CliMode.Exec, "Troubleshoot", "show logging last 50"),
    ]);

    private static CliVendor CiscoAsa() => new("cisco-asa", "Cisco ASA", "asa#",
    [
        C("show running-config", "Display the running configuration.", CliMode.Privileged, "Show & verify", "show running-config [<feature>]", "show running-config access-list"),
        C("show interface ip brief", "One-line IP/status per interface.", CliMode.Privileged, "Show & verify"),
        C("show nameif", "Interface names and security levels.", CliMode.Privileged, "Show & verify"),
        C("show version", "ASA version, model and licensing.", CliMode.Privileged, "Show & verify"),
        C("show access-list", "ACLs with hit counts.", CliMode.Privileged, "Security", "show access-list [<name>]"),
        C("show conn", "Active connections through the firewall.", CliMode.Privileged, "Security", "show conn [address <ip>]"),
        C("show xlate", "Active NAT translations.", CliMode.Privileged, "Security"),
        C("show route", "The routing table.", CliMode.Privileged, "Routing"),
        C("show vpn-sessiondb", "Active VPN sessions (AnyConnect/IPsec).", CliMode.Privileged, "VPN", "show vpn-sessiondb anyconnect"),
        C("show crypto isakmp sa", "IKE phase-1 security associations.", CliMode.Privileged, "VPN"),
        C("show crypto ipsec sa", "IPsec phase-2 security associations.", CliMode.Privileged, "VPN"),
        C("configure terminal", "Enter global configuration mode.", CliMode.Privileged, "Config basics"),
        C("interface <if>", "Enter interface config.", CliMode.Config, "Interfaces", "interface GigabitEthernet0/0"),
        C("nameif <name>", "Name the interface (inside/outside/dmz).", CliMode.ConfigInterface, "Interfaces", "nameif outside"),
        C("security-level <0-100>", "Set the interface trust level.", CliMode.ConfigInterface, "Interfaces", "security-level 0"),
        C("ip address <ip> <mask>", "Assign an IP to the interface.", CliMode.ConfigInterface, "Interfaces", "ip address 203.0.113.2 255.255.255.0"),
        C("object network <name>", "Define a network object (host/subnet/range).", CliMode.Config, "Security", "object network WEB\n host 10.1.1.10"),
        C("access-list <name> ...", "Define an ACL entry.", CliMode.Config, "Security", "access-list OUTSIDE_IN extended permit tcp any host 10.1.1.10 eq 443"),
        C("access-group <acl> in interface <if>", "Apply an ACL to an interface.", CliMode.Config, "Security", "access-group OUTSIDE_IN in interface outside"),
        C("write memory", "Save the configuration.", CliMode.Privileged, "Save & manage", "write memory"),
        C("packet-tracer input <if> ...", "Simulate a packet through the policy.", CliMode.Privileged, "Troubleshoot", "packet-tracer input outside tcp 1.1.1.1 1234 10.1.1.10 443"),
        C("ping <host>", "ICMP reachability test.", CliMode.Privileged, "Troubleshoot", "ping outside 8.8.8.8"),
    ]);

    private static CliVendor AristaEos() => new("arista-eos", "Arista EOS", "switch#",
    [
        C("show running-config", "Display the running configuration.", CliMode.Privileged, "Show & verify", "show running-config [section <text>]"),
        C("show interfaces status", "Switchport status table.", CliMode.Exec, "Show & verify"),
        C("show ip interface brief", "One-line IP/status per interface.", CliMode.Exec, "Show & verify"),
        C("show version", "EOS version and hardware.", CliMode.Exec, "Show & verify"),
        C("show vlan", "VLANs and ports.", CliMode.Exec, "Switching"),
        C("show ip route", "IPv4 routing table.", CliMode.Exec, "Routing"),
        C("show ip bgp summary", "BGP neighbor summary.", CliMode.Exec, "Routing"),
        C("show mlag", "MLAG domain and peer status.", CliMode.Exec, "Switching"),
        C("show lldp neighbors", "Connected LLDP devices.", CliMode.Exec, "Discovery"),
        C("configure", "Enter configuration mode.", CliMode.Privileged, "Config basics"),
        C("interface <if>", "Enter interface config.", CliMode.Config, "Interfaces", "interface Ethernet1"),
        C("ip address <ip>/<prefix>", "Assign an IP address.", CliMode.ConfigInterface, "Interfaces", "ip address 10.0.0.1/24"),
        C("no shutdown", "Enable the interface.", CliMode.ConfigInterface, "Interfaces"),
        C("switchport access vlan <id>", "Assign an access VLAN.", CliMode.ConfigInterface, "Switching", "switchport access vlan 20"),
        C("vlan <id>", "Create a VLAN.", CliMode.Config, "Switching", "vlan 20"),
        C("router bgp <as>", "Enter BGP config.", CliMode.Config, "Routing", "router bgp 65001"),
        C("write memory", "Save the configuration.", CliMode.Privileged, "Save & manage", "write memory", "copy running-config startup-config"),
        C("ping <host>", "ICMP reachability test.", CliMode.Exec, "Troubleshoot", "ping 8.8.8.8"),
        C("bash", "Drop to the underlying Linux shell.", CliMode.Privileged, "Troubleshoot"),
    ]);
}
